# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56fa65dcd7e97e85cbc5580989cd3a19a996cc4a77ef75aa36efc49d236e4e973ffc9778031b24ef282a5d9bf5da52708cbedc486977dd8a885f7bad5a1cc6d7

test:
  secret_key_base: 340f85b082efd275ebb6f3ab3603ff7a24a7243beca29370e3dfd85a6ba80d1772af72a7b5b74267cf779394995809ab8cbeced6c0850cff3845046dcb204f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
